### ISSUE TITLE
Exposure Notification enabling pop-up did not appear on iOS?

### ISSUE THREAD

**Issue by muhdlaziem** [CovidShield/mobile#132] opened 2020-06-19 01:36 UTC
To enable the exposure notification, a pop up message will appear asking user to enable exposure notification. In my case, the pop up message did not appear on iOS but does appear on Android

**Comment by yingsean** [comment] 2020-06-20 13:32
It's not a bug. Missing entitlements in the CovidShield.entitlements file.
Modified to following:

```
<plist version="1.0">
<dict>
	<key>com.apple.developer.exposure-notification</key>
	<true/>
	<key>com.apple.developer.exposure-notification-test</key>
	<true/>
</dict>
</plist>
```

**Comment by henrytao-me** [comment] 2020-06-24 01:15
I will close this then. 🙇

**Closed by henrytao-me** 2020-06-24 01:15 UTC
Labels: bug, iOS
